#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_TekSuit_Gen2_Cosmetic

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Buff_TekSuit_Gen2_Cosmetic.Buff_TekSuit_Gen2_Cosmetic_C
// 0x0000 (0x09C0 - 0x09C0)
class ABuff_TekSuit_Gen2_Cosmetic_C final : public APrimalBuff
{
public:
	void BuffTickClient(float DeltaTime);
	bool AllowPostProcessEffect();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_TekSuit_Gen2_Cosmetic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"Buff_TekSuit_Gen2_Cosmetic_C")
	}
	static class ABuff_TekSuit_Gen2_Cosmetic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_TekSuit_Gen2_Cosmetic_C>();
	}
};

SDK_NAMESPACE_END
