#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_TekSuit_Gen2_Cosmetic

#include "Basic.hpp"

#include "Buff_TekSuit_Gen2_Cosmetic_classes.hpp"
#include "Buff_TekSuit_Gen2_Cosmetic_parameters.hpp"


SDK_NAMESPACE_START

// Function Buff_TekSuit_Gen2_Cosmetic.Buff_TekSuit_Gen2_Cosmetic_C.BuffTickClient
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_TekSuit_Gen2_Cosmetic_C::BuffTickClient(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_TekSuit_Gen2_Cosmetic_C", "BuffTickClient");

	Params::Buff_TekSuit_Gen2_Cosmetic_C_BuffTickClient Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_TekSuit_Gen2_Cosmetic.Buff_TekSuit_Gen2_Cosmetic_C.AllowPostProcessEffect
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool ABuff_TekSuit_Gen2_Cosmetic_C::AllowPostProcessEffect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_TekSuit_Gen2_Cosmetic_C", "AllowPostProcessEffect");

	Params::Buff_TekSuit_Gen2_Cosmetic_C_AllowPostProcessEffect Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
