#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_NotifyHoversailFollow

#include "Basic.hpp"

#include "Buff_Base_classes.hpp"
#include "ShooterGame_structs.hpp"
#include "Slate_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Buff_NotifyHoversailFollow.Buff_NotifyHoversailFollow_C
// 0x01D8 (0x0B98 - 0x09C0)
class ABuff_NotifyHoversailFollow_C final : public ABuff_Base_C
{
public:
	class APrimalCharacter*                       HoverSail;                                         // 0x09C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Lastpassedlocation;                                // 0x09C8(0x000C)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          hoversail_has_been_set;                            // 0x09D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9D5[0x3];                                      // 0x09D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 follow_string;                                     // 0x09D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 follow_string_stasis_d;                            // 0x09E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	struct FVector2D                              TeleWorldHUDElementSize;                           // 0x09F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TeleWorldIndicatorSizeMult;                        // 0x0A00(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAnchors                               TeleWorldHUDElementAnchor;                         // 0x0A04(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)
	bool                                          has_stasis_d;                                      // 0x0A14(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A15[0x3];                                      // 0x0A15(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FHUDElement                            LocationIndicatorHUDElementTemplate;               // 0x0A18(0x0150)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FVector                                MaxHUDIndicatorWorldOffset;                        // 0x0B68(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxDistanceForHUDLocationIndicatorScaling;         // 0x0B74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                MinHUDIndicatorWorldOffset;                        // 0x0B78(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaxHUDLocationIndicatorScale;                      // 0x0B84(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MinHUDLocationIndicatorScale;                      // 0x0B88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              InterpedScreenPos;                                 // 0x0B8C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BuffTickClient(float DeltaTime);
	void BuffTickServer(float DeltaTime);
	void Set_and_Pass_Loc();
	void BPGetHUDElements(class APlayerController* ForPC, TArray<struct FHUDElement>* OutElements);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_NotifyHoversailFollow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"Buff_NotifyHoversailFollow_C")
	}
	static class ABuff_NotifyHoversailFollow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_NotifyHoversailFollow_C>();
	}
};

SDK_NAMESPACE_END
