#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_BasedOnDesertKaiju

#include "Basic.hpp"

#include "Buff_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Buff_BasedOnDesertKaiju.Buff_BasedOnDesertKaiju_C
// 0x0008 (0x09C8 - 0x09C0)
class ABuff_BasedOnDesertKaiju_C final : public ABuff_Base_C
{
public:
	float                                         CachedMaxWalkSpeed;                                // 0x09C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BPSetupForInstigator(class AActor* ForInstigator);
	void BPDeactivated(class AActor* ForInstigator);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_BasedOnDesertKaiju_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"Buff_BasedOnDesertKaiju_C")
	}
	static class ABuff_BasedOnDesertKaiju_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_BasedOnDesertKaiju_C>();
	}
};

SDK_NAMESPACE_END
