#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CORE_PrimalGameData

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"
#include "HairMetaData_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CORE_PrimalGameData.CORE_PrimalGameData_C
// 0x0020 (0x21B8 - 0x2198)
class UCORE_PrimalGameData_C : public UPrimalGameData
{
public:
	TArray<struct FHairMetaData>                  FemaleHairStylesMetaDatas;                         // 0x2198(0x0010)(Edit, BlueprintVisible)
	TArray<struct FHairMetaData>                  MaleHairStylesMetaDatas;                           // 0x21A8(0x0010)(Edit, BlueprintVisible)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CORE_PrimalGameData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CORE_PrimalGameData_C")
	}
	static class UCORE_PrimalGameData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCORE_PrimalGameData_C>();
	}
};

SDK_NAMESPACE_END
