#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DamageType_UnsubmergedRecoverOxygen

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DamageType_UnsubmergedRecoverOxygen.DamageType_UnsubmergedRecoverOxygen_C
// 0x0000 (0x0140 - 0x0140)
class UDamageType_UnsubmergedRecoverOxygen_C final : public UShooterDamageType
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DamageType_UnsubmergedRecoverOxygen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"DamageType_UnsubmergedRecoverOxygen_C")
	}
	static class UDamageType_UnsubmergedRecoverOxygen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDamageType_UnsubmergedRecoverOxygen_C>();
	}
};

SDK_NAMESPACE_END
