#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataListEntryWidgetGeneric_Engram

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass DataListEntryWidgetGeneric_Engram.DataListEntryWidgetGeneric_Engram_C
// 0x0008 (0x03C8 - 0x03C0)
class UDataListEntryWidgetGeneric_Engram_C final : public UDataListEntryWidget
{
public:
	class UDataListEntryButton_CustomOverlay*     MyDataListButton;                                  // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DataListEntryWidgetGeneric_Engram_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"DataListEntryWidgetGeneric_Engram_C")
	}
	static class UDataListEntryWidgetGeneric_Engram_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDataListEntryWidgetGeneric_Engram_C>();
	}
};

SDK_NAMESPACE_END
