#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataListEntryWidgetGeneric_DyeResources

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass DataListEntryWidgetGeneric_DyeResources.DataListEntryWidgetGeneric_DyeResources_C
// 0x0008 (0x0658 - 0x0650)
class UDataListEntryWidgetGeneric_DyeResources_C final : public UDataListEntryButton_DyeResources
{
public:
	class UImage*                                 ItemIcon;                                          // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DataListEntryWidgetGeneric_DyeResources_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"DataListEntryWidgetGeneric_DyeResources_C")
	}
	static class UDataListEntryWidgetGeneric_DyeResources_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDataListEntryWidgetGeneric_DyeResources_C>();
	}
};

SDK_NAMESPACE_END
