#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_TekGlovePunchState

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum E_TekGlovePunchState.E_TekGlovePunchState
// NumValues: 0x0006
enum class E_TekGlovePunchState : uint8
{
	NewEnumerator0                           = static_cast<uint8>(0),
	NewEnumerator1                           = static_cast<uint8>(1),
	NewEnumerator4                           = static_cast<uint8>(2),
	NewEnumerator5                           = static_cast<uint8>(3),
	NewEnumerator6                           = static_cast<uint8>(4),
	E_MAX                                    = static_cast<uint8>(5),
};

SDK_NAMESPACE_END
