#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EmoteRadialSelectorBP

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EmoteRadialSelectorBP.EmoteRadialSelectorBP_C
// 0x0000 (0x0138 - 0x0138)
class UEmoteRadialSelectorBP_C final : public URadialSelectorHUD_PlayerAction
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EmoteRadialSelectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"EmoteRadialSelectorBP_C")
	}
	static class UEmoteRadialSelectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEmoteRadialSelectorBP_C>();
	}
};

SDK_NAMESPACE_END
