#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_MetalPipeIntersection

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EngramEntry_MetalPipeIntersection.EngramEntry_MetalPipeIntersection_C
// 0x0000 (0x0090 - 0x0090)
class UEngramEntry_MetalPipeIntersection_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EngramEntry_MetalPipeIntersection_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"EngramEntry_MetalPipeIntersection_C")
	}
	static class UEngramEntry_MetalPipeIntersection_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_MetalPipeIntersection_C>();
	}
};

SDK_NAMESPACE_END
