#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EngramEntry_TaxidermyBase_Large

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass EngramEntry_TaxidermyBase_Large.EngramEntry_TaxidermyBase_Large_C
// 0x0000 (0x0090 - 0x0090)
class UEngramEntry_TaxidermyBase_Large_C final : public UPrimalEngramEntry
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("EngramEntry_TaxidermyBase_Large_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"EngramEntry_TaxidermyBase_Large_C")
	}
	static class UEngramEntry_TaxidermyBase_Large_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEngramEntry_TaxidermyBase_Large_C>();
	}
};

SDK_NAMESPACE_END
