#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameCheatButtonBase

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass GameCheatButtonBase.GameCheatButtonBase_C
// 0x0000 (0x0308 - 0x0308)
class UGameCheatButtonBase_C : public UUI_CheatButton
{
public:
	void SetupUI(class UGameCheatUI_C* WithParent);
	void ButtonUpdateUI();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GameCheatButtonBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GameCheatButtonBase_C")
	}
	static class UGameCheatButtonBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGameCheatButtonBase_C>();
	}
};

SDK_NAMESPACE_END
