#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HackCraftUI

#include "Basic.hpp"

#include "HackCraftUI_classes.hpp"
#include "HackCraftUI_parameters.hpp"


SDK_NAMESPACE_START

// Function HackCraftUI.HackCraftUI_C.ExecuteUbergraph_HackCraftUI
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHackCraftUI_C::ExecuteUbergraph_HackCraftUI(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "ExecuteUbergraph_HackCraftUI");

	Params::HackCraftUI_C_ExecuteUbergraph_HackCraftUI Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HackCraftUI.HackCraftUI_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHackCraftUI_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "Tick");

	Params::HackCraftUI_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HackCraftUI.HackCraftUI_C.BndEvt__HackCraftUI_RemoveOne_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UHackCraftUI_C::BndEvt__HackCraftUI_RemoveOne_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "BndEvt__HackCraftUI_RemoveOne_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HackCraftUI.HackCraftUI_C.BndEvt__HackCraftUI_AddOne_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UHackCraftUI_C::BndEvt__HackCraftUI_AddOne_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "BndEvt__HackCraftUI_AddOne_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HackCraftUI.HackCraftUI_C.UpdateKeysNeeded
// (BlueprintCallable, BlueprintEvent)

void UHackCraftUI_C::UpdateKeysNeeded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "UpdateKeysNeeded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HackCraftUI.HackCraftUI_C.SetHackCraft
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUI_Inventory*                    inventoryUI                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimalItem*                      ForItem                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UHackCraftUI_C::SetHackCraft(class UUI_Inventory* inventoryUI, class UPrimalItem* ForItem)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "SetHackCraft");

	Params::HackCraftUI_C_SetHackCraft Parms{};

	Parms.inventoryUI = inventoryUI;
	Parms.ForItem = ForItem;

	UObject::ProcessEvent(Func, &Parms);
}


// Function HackCraftUI.HackCraftUI_C.BndEvt__ConfirmKeyPurchaseUI_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UHackCraftUI_C::BndEvt__ConfirmKeyPurchaseUI_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "BndEvt__ConfirmKeyPurchaseUI_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function HackCraftUI.HackCraftUI_C.BndEvt__ConfirmKeyPurchaseUI_OkButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UHackCraftUI_C::BndEvt__ConfirmKeyPurchaseUI_OkButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("HackCraftUI_C", "BndEvt__ConfirmKeyPurchaseUI_OkButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
