#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HUDCustomStatusUI

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass HUDCustomStatusUI.HUDCustomStatusUI_C
// 0x0008 (0x0710 - 0x0708)
class UHUDCustomStatusUI_C final : public UHUDCustomStatusWidget
{
public:
	class UCanvasPanel*                           CustomStatusCanvasPanel;                           // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HUDCustomStatusUI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"HUDCustomStatusUI_C")
	}
	static class UHUDCustomStatusUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHUDCustomStatusUI_C>();
	}
};

SDK_NAMESPACE_END
