#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HurtCameraShake

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass HurtCameraShake.HurtCameraShake_C
// 0x0000 (0x01D0 - 0x01D0)
class UHurtCameraShake_C final : public UMatineeCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HurtCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"HurtCameraShake_C")
	}
	static class UHurtCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHurtCameraShake_C>();
	}
};

SDK_NAMESPACE_END
