#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Key_HatchEgg

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Key_HatchEgg.Key_HatchEgg_C
// 0x0000 (0x0120 - 0x0120)
class UKey_HatchEgg_C final : public UHatchEggInsertion
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Key_HatchEgg_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"Key_HatchEgg_C")
	}
	static class UKey_HatchEgg_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKey_HatchEgg_C>();
	}
};

SDK_NAMESPACE_END
