#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeleeStoneWeapon_Impacts

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass MeleeStoneWeapon_Impacts.MeleeStoneWeapon_Impacts_C
// 0x0008 (0x0770 - 0x0768)
class AMeleeStoneWeapon_Impacts_C final : public AShooterImpactEffect
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MeleeStoneWeapon_Impacts_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"MeleeStoneWeapon_Impacts_C")
	}
	static class AMeleeStoneWeapon_Impacts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMeleeStoneWeapon_Impacts_C>();
	}
};

SDK_NAMESPACE_END
