#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionsUI_Entry

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass MissionsUI_Entry.MissionsUI_Entry_C
// 0x0028 (0x0688 - 0x0660)
class UMissionsUI_Entry_C final : public UMissionListEntryWidget
{
public:
	class UImage*                                 Image_216;                                         // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCustomButtonWidget*                    MissionEntryButton;                                // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             MissionNameText;                                   // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 MissionTypeIconImage;                              // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PlayersIcon;                                       // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionsUI_Entry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"MissionsUI_Entry_C")
	}
	static class UMissionsUI_Entry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionsUI_Entry_C>();
	}
};

SDK_NAMESPACE_END
