#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayInAppReviews

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum PlayInAppReviews.EInAppReviewErrorCode
// NumValues: 0x000A
enum class EInAppReviewErrorCode : uint8
{
	Review_NO_ERROR                          = static_cast<uint8>(0),
	Review_INITIALIZATION_NEEDED             = static_cast<uint8>(1),
	Review_INITIALIZATION_FAILED             = static_cast<uint8>(2),
	Review_REQUEST_FLOW_NEEDED               = static_cast<uint8>(3),
	Review_REQUEST_FLOW_FAILED               = static_cast<uint8>(4),
	Review_INVALID_REQUEST                   = static_cast<uint8>(5),
	Review_PLAY_STORE_NOT_FOUND              = static_cast<uint8>(6),
	Review_UNKNOWN                           = static_cast<uint8>(7),
	Review_REQUEST_CANCELED                  = static_cast<uint8>(8),
	Review_MAX                               = static_cast<uint8>(9),
};

// Enum PlayInAppReviews.EInAppReviewStatus
// NumValues: 0x0006
enum class EInAppReviewStatus : uint8
{
	Review_STATUS_UNKNOWN                    = static_cast<uint8>(0),
	Review_REQUEST_FLOW_PENDING              = static_cast<uint8>(1),
	Review_REQUEST_FLOW_COMPLETED            = static_cast<uint8>(2),
	Review_LAUNCH_FLOW_PENDING               = static_cast<uint8>(3),
	Review_LAUNCH_FLOW_COMPLETED             = static_cast<uint8>(4),
	Review_MAX                               = static_cast<uint8>(5),
};

SDK_NAMESPACE_END
