#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumableRespecSoup

#include "Basic.hpp"

#include "PrimalItemConsumableEatable_BuffingSoup_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemConsumableRespecSoup.PrimalItemConsumableRespecSoup_C
// 0x0018 (0x0D68 - 0x0D50)
class UPrimalItemConsumableRespecSoup_C final : public UPrimalItemConsumableEatable_BuffingSoup_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D50(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UPrimalItem*                            SelfObj;                                           // 0x0D58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          UseRespecCooldown;                                 // 0x0D60(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D61[0x3];                                      // 0x0D61(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CooldownTimeInSeconds;                             // 0x0D64(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PrimalItemConsumableRespecSoup(int32 EntryPoint);
	void BlueprintUsed();
	bool BPCanUse(bool bIgnoreCooldown);
	void GetLastRespecTime(struct FBlueprintDouble* LastRespecUtcTime);
	class FString BPGetCustomInventoryWidgetText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumableRespecSoup_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemConsumableRespecSoup_C")
	}
	static class UPrimalItemConsumableRespecSoup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumableRespecSoup_C>();
	}
};

SDK_NAMESPACE_END
