#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumableSeed

#include "Basic.hpp"

#include "PrimalItemConsumableEatable_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemConsumableSeed.PrimalItemConsumableSeed_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemConsumableSeed_C : public UPrimalItemConsumableEatable_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumableSeed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemConsumableSeed_C")
	}
	static class UPrimalItemConsumableSeed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumableSeed_C>();
	}
};

SDK_NAMESPACE_END
