#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_EquusSaddle

#include "Basic.hpp"

#include "PrimalItemArmor_SaddleGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_EquusSaddle.PrimalItemArmor_EquusSaddle_C
// 0x0000 (0x0D58 - 0x0D58)
class UPrimalItemArmor_EquusSaddle_C final : public UPrimalItemArmor_SaddleGeneric_C
{
public:
	void BlueprintUnequipped();
	void BlueprintEquipped(bool bIsFromSaveGame);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_EquusSaddle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_EquusSaddle_C")
	}
	static class UPrimalItemArmor_EquusSaddle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_EquusSaddle_C>();
	}
};

SDK_NAMESPACE_END
