#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_ElevatorPlatformSmall

#include "Basic.hpp"

#include "PrimalItemStructure_ElevatorPlatformBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_ElevatorPlatformSmall.PrimalItemStructure_ElevatorPlatformSmall_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_ElevatorPlatformSmall_C final : public UPrimalItemStructure_ElevatorPlatformBase_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_ElevatorPlatformSmall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_ElevatorPlatformSmall_C")
	}
	static class UPrimalItemStructure_ElevatorPlatformSmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_ElevatorPlatformSmall_C>();
	}
};

SDK_NAMESPACE_END
