#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_NightVisionGoggles

#include "Basic.hpp"

#include "PrimalItemArmor_BaseHelmet_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_NightVisionGoggles.PrimalItemArmor_NightVisionGoggles_C
// 0x0018 (0x0D68 - 0x0D50)
class UPrimalItemArmor_NightVisionGoggles_C final : public UPrimalItemArmor_BaseHelmet_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D50(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UClass*                                 EquippedBuff;                                      // 0x0D58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPrimalItem*                            SelfObj;                                           // 0x0D60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PrimalItemArmor_NightVisionGoggles(int32 EntryPoint);
	void BlueprintUnequipped();
	void BlueprintEquipped(bool bIsFromSaveGame);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_NightVisionGoggles_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_NightVisionGoggles_C")
	}
	static class UPrimalItemArmor_NightVisionGoggles_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_NightVisionGoggles_C>();
	}
};

SDK_NAMESPACE_END
