#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_RexSaddle_Tek

#include "Basic.hpp"

#include "PrimalItemArmor_SaddleGeneric_Tek_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_RexSaddle_Tek.PrimalItemArmor_RexSaddle_Tek_C
// 0x0000 (0x0D98 - 0x0D98)
class UPrimalItemArmor_RexSaddle_Tek_C final : public UPrimalItemArmor_SaddleGeneric_Tek_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_RexSaddle_Tek_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_RexSaddle_Tek_C")
	}
	static class UPrimalItemArmor_RexSaddle_Tek_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_RexSaddle_Tek_C>();
	}
};

SDK_NAMESPACE_END
