#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_Costume_MutatedSurvivor

#include "Basic.hpp"

#include "PrimalItemSkin_FullCostumeTest_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkin_Costume_MutatedSurvivor.PrimalItemSkin_Costume_MutatedSurvivor_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemSkin_Costume_MutatedSurvivor_C final : public UPrimalItemSkin_FullCostumeTest_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_Costume_MutatedSurvivor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkin_Costume_MutatedSurvivor_C")
	}
	static class UPrimalItemSkin_Costume_MutatedSurvivor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_Costume_MutatedSurvivor_C>();
	}
};

SDK_NAMESPACE_END
