#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_HideGloves

#include "Basic.hpp"

#include "PrimalItemArmor_BaseGloves_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_HideGloves.PrimalItemArmor_HideGloves_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemArmor_HideGloves_C final : public UPrimalItemArmor_BaseGloves_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_HideGloves_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_HideGloves_C")
	}
	static class UPrimalItemArmor_HideGloves_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_HideGloves_C>();
	}
};

SDK_NAMESPACE_END
