#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumableMiracleGro

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PrimalItemConsumableEatable_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemConsumableMiracleGro.PrimalItemConsumableMiracleGro_C
// 0x0038 (0x0D88 - 0x0D50)
class UPrimalItemConsumableMiracleGro_C final : public UPrimalItemConsumableEatable_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0D50(0x0008)(ZeroConstructor, Transient, DuplicateTransient, UObjectWrapper)
	class UPrimalItem*                            SelfObj;                                           // 0x0D58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Max_Repopulation_Range;                            // 0x0D60(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Max_Foliages_To_Repopulate;                        // 0x0D64(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                StructureDownTraceVector;                          // 0x0D68(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                StructureUpTraceVector;                            // 0x0D74(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClass*                                 Repopulation_Emitter;                              // 0x0D80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PrimalItemConsumableMiracleGro(int32 EntryPoint);
	void BlueprintUsed();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumableMiracleGro_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemConsumableMiracleGro_C")
	}
	static class UPrimalItemConsumableMiracleGro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumableMiracleGro_C>();
	}
};

SDK_NAMESPACE_END
