#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_AdobeWallWithWindow

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWallWithWindow_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_AdobeWallWithWindow.PrimalItemStructure_AdobeWallWithWindow_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_AdobeWallWithWindow_C final : public UPrimalItemStructure_BaseWallWithWindow_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_AdobeWallWithWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_AdobeWallWithWindow_C")
	}
	static class UPrimalItemStructure_AdobeWallWithWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_AdobeWallWithWindow_C>();
	}
};

SDK_NAMESPACE_END
