#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponTekGrenadeLauncher

#include "Basic.hpp"

#include "PrimalItemWeaponGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_WeaponTekGrenadeLauncher.PrimalItem_WeaponTekGrenadeLauncher_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItem_WeaponTekGrenadeLauncher_C final : public UPrimalItemWeaponGeneric_C
{
public:
	class FString BPGetCustomInventoryWidgetText();
	class FString BPGetItemDescription(const class FString& InDescription, bool bGetLongDescription, class AShooterPlayerController* ForPC);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponTekGrenadeLauncher_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_WeaponTekGrenadeLauncher_C")
	}
	static class UPrimalItem_WeaponTekGrenadeLauncher_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponTekGrenadeLauncher_C>();
	}
};

SDK_NAMESPACE_END
