#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponGun

#include "Basic.hpp"

#include "PrimalItemWeaponGenericGun_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_WeaponGun.PrimalItem_WeaponGun_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItem_WeaponGun_C final : public UPrimalItemWeaponGenericGun_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponGun_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_WeaponGun_C")
	}
	static class UPrimalItem_WeaponGun_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponGun_C>();
	}
};

SDK_NAMESPACE_END
