#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_WoodWindow

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWindow_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_WoodWindow.PrimalItemStructure_WoodWindow_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_WoodWindow_C final : public UPrimalItemStructure_BaseWindow_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_WoodWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_WoodWindow_C")
	}
	static class UPrimalItemStructure_WoodWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_WoodWindow_C>();
	}
};

SDK_NAMESPACE_END
