#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_BaseRamp

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_BaseRamp.PrimalItemStructure_BaseRamp_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_BaseRamp_C : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_BaseRamp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_BaseRamp_C")
	}
	static class UPrimalItemStructure_BaseRamp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_BaseRamp_C>();
	}
};

SDK_NAMESPACE_END
