#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_StonePipeIncline

#include "Basic.hpp"

#include "PrimalItemStructure_BaseStonePipe_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_StonePipeIncline.PrimalItemStructure_StonePipeIncline_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_StonePipeIncline_C final : public UPrimalItemStructure_BaseStonePipe_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_StonePipeIncline_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_StonePipeIncline_C")
	}
	static class UPrimalItemStructure_StonePipeIncline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_StonePipeIncline_C>();
	}
};

SDK_NAMESPACE_END
