#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemResource_AnglerGel

#include "Basic.hpp"

#include "PrimalItemResourceGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemResource_AnglerGel.PrimalItemResource_AnglerGel_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemResource_AnglerGel_C final : public UPrimalItemResourceGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemResource_AnglerGel_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemResource_AnglerGel_C")
	}
	static class UPrimalItemResource_AnglerGel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemResource_AnglerGel_C>();
	}
};

SDK_NAMESPACE_END
