#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_TekGrenade

#include "Basic.hpp"

#include "PrimalItemWeaponGenericAmmolessConsumeSelf_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_TekGrenade.PrimalItem_TekGrenade_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItem_TekGrenade_C final : public UPrimalItemWeaponGenericAmmolessConsumeSelf_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_TekGrenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_TekGrenade_C")
	}
	static class UPrimalItem_TekGrenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_TekGrenade_C>();
	}
};

SDK_NAMESPACE_END
