#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemDye_Forest

#include "Basic.hpp"

#include "PrimalItemDyeGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemDye_Forest.PrimalItemDye_Forest_C
// 0x0000 (0x0D70 - 0x0D70)
class UPrimalItemDye_Forest_C final : public UPrimalItemDyeGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemDye_Forest_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemDye_Forest_C")
	}
	static class UPrimalItemDye_Forest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemDye_Forest_C>();
	}
};

SDK_NAMESPACE_END
