#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_MetalSpikeWall

#include "Basic.hpp"

#include "PrimalItemStructureGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_MetalSpikeWall.PrimalItemStructure_MetalSpikeWall_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_MetalSpikeWall_C final : public UPrimalItemStructureGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_MetalSpikeWall_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_MetalSpikeWall_C")
	}
	static class UPrimalItemStructure_MetalSpikeWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_MetalSpikeWall_C>();
	}
};

SDK_NAMESPACE_END
