#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkinGeneric

#include "Basic.hpp"

#include "PrimalItem_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkinGeneric.PrimalItemSkinGeneric_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemSkinGeneric_C : public UPrimalItem_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkinGeneric_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkinGeneric_C")
	}
	static class UPrimalItemSkinGeneric_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkinGeneric_C>();
	}
};

SDK_NAMESPACE_END
