#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponStoneClub

#include "Basic.hpp"

#include "PrimalItem_WeaponBaseClub_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_WeaponStoneClub.PrimalItem_WeaponStoneClub_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItem_WeaponStoneClub_C final : public UPrimalItem_WeaponBaseClub_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponStoneClub_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_WeaponStoneClub_C")
	}
	static class UPrimalItem_WeaponStoneClub_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponStoneClub_C>();
	}
};

SDK_NAMESPACE_END
