#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_HomoDeusHelmet

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkin_HomoDeusHelmet.PrimalItemSkin_HomoDeusHelmet_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemSkin_HomoDeusHelmet_C final : public UPrimalItemSkinGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_HomoDeusHelmet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkin_HomoDeusHelmet_C")
	}
	static class UPrimalItemSkin_HomoDeusHelmet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_HomoDeusHelmet_C>();
	}
};

SDK_NAMESPACE_END
