#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_TekShirt_V2

#include "Basic.hpp"

#include "PrimalItemSkin_TekShirt_V2_classes.hpp"
#include "PrimalItemSkin_TekShirt_V2_parameters.hpp"


SDK_NAMESPACE_START

// Function PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C.BlueprintUnequipped
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UPrimalItemSkin_TekShirt_V2_C::BlueprintUnequipped()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TekShirt_V2_C", "BlueprintUnequipped");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C.BlueprintEquipped
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bIsFromSaveGame                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPrimalItemSkin_TekShirt_V2_C::BlueprintEquipped(bool bIsFromSaveGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TekShirt_V2_C", "BlueprintEquipped");

	Params::PrimalItemSkin_TekShirt_V2_C_BlueprintEquipped Parms{};

	Parms.bIsFromSaveGame = bIsFromSaveGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C.RemovedSkinFromItem
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimalItem*                      FromOwnerItem                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsFirstTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPrimalItemSkin_TekShirt_V2_C::RemovedSkinFromItem(class UPrimalItem* FromOwnerItem, bool bIsFirstTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TekShirt_V2_C", "RemovedSkinFromItem");

	Params::PrimalItemSkin_TekShirt_V2_C_RemovedSkinFromItem Parms{};

	Parms.FromOwnerItem = FromOwnerItem;
	Parms.bIsFirstTime = bIsFirstTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C.ApplyingSkinOntoItem
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimalItem*                      ToOwnerItem                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bIsFirstTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPrimalItemSkin_TekShirt_V2_C::ApplyingSkinOntoItem(class UPrimalItem* ToOwnerItem, bool bIsFirstTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TekShirt_V2_C", "ApplyingSkinOntoItem");

	Params::PrimalItemSkin_TekShirt_V2_C_ApplyingSkinOntoItem Parms{};

	Parms.ToOwnerItem = ToOwnerItem;
	Parms.bIsFirstTime = bIsFirstTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C.TrySetTeksuitVFXOffset
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Unequip                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPrimalItemSkin_TekShirt_V2_C::TrySetTeksuitVFXOffset(bool Unequip)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TekShirt_V2_C", "TrySetTeksuitVFXOffset");

	Params::PrimalItemSkin_TekShirt_V2_C_TrySetTeksuitVFXOffset Parms{};

	Parms.Unequip = Unequip;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
