#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_TorchSparkler

#include "Basic.hpp"

#include "PrimalItemSkin_TorchSparkler_classes.hpp"
#include "PrimalItemSkin_TorchSparkler_parameters.hpp"


SDK_NAMESPACE_START

// Function PrimalItemSkin_TorchSparkler.PrimalItemSkin_TorchSparkler_C.BPGetFuelParticleSystemOverride
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APrimalStructure*                 ForStructure                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UParticleSystem*                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UParticleSystem* UPrimalItemSkin_TorchSparkler_C::BPGetFuelParticleSystemOverride(class APrimalStructure* ForStructure)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TorchSparkler_C", "BPGetFuelParticleSystemOverride");

	Params::PrimalItemSkin_TorchSparkler_C_BPGetFuelParticleSystemOverride Parms{};

	Parms.ForStructure = ForStructure;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PrimalItemSkin_TorchSparkler.PrimalItemSkin_TorchSparkler_C.BPGetFuelAudioOverride
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APrimalStructure*                 ForStructure                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class USoundBase*                       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class USoundBase* UPrimalItemSkin_TorchSparkler_C::BPGetFuelAudioOverride(class APrimalStructure* ForStructure)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PrimalItemSkin_TorchSparkler_C", "BPGetFuelAudioOverride");

	Params::PrimalItemSkin_TorchSparkler_C_BPGetFuelAudioOverride Parms{};

	Parms.ForStructure = ForStructure;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
