#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_SpineyLizardPromoSaddle

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_SpineyLizardPromoSaddle.PrimalItemArmor_SpineyLizardPromoSaddle_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemArmor_SpineyLizardPromoSaddle_C final : public UPrimalItemSkinGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_SpineyLizardPromoSaddle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_SpineyLizardPromoSaddle_C")
	}
	static class UPrimalItemArmor_SpineyLizardPromoSaddle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_SpineyLizardPromoSaddle_C>();
	}
};

SDK_NAMESPACE_END
