#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_TurkeyHat

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_Trophy_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkin_TurkeyHat.PrimalItemSkin_TurkeyHat_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemSkin_TurkeyHat_C final : public UPrimalItemSkinGeneric_Trophy_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_TurkeyHat_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkin_TurkeyHat_C")
	}
	static class UPrimalItemSkin_TurkeyHat_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_TurkeyHat_C>();
	}
};

SDK_NAMESPACE_END
