#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemConsumable_TekCanteenRefill

#include "Basic.hpp"

#include "PrimalItemConsumable_TekCanteenCraftable_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemConsumable_TekCanteenRefill.PrimalItemConsumable_TekCanteenRefill_C
// 0x0000 (0x0DE0 - 0x0DE0)
class UPrimalItemConsumable_TekCanteenRefill_C final : public UPrimalItemConsumable_TekCanteenCraftable_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemConsumable_TekCanteenRefill_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemConsumable_TekCanteenRefill_C")
	}
	static class UPrimalItemConsumable_TekCanteenRefill_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemConsumable_TekCanteenRefill_C>();
	}
};

SDK_NAMESPACE_END
