#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_StoneStairs

#include "Basic.hpp"

#include "PrimalItemStructure_BaseWall_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_StoneStairs.PrimalItemStructure_StoneStairs_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_StoneStairs_C final : public UPrimalItemStructure_BaseWall_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_StoneStairs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_StoneStairs_C")
	}
	static class UPrimalItemStructure_StoneStairs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_StoneStairs_C>();
	}
};

SDK_NAMESPACE_END
