#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponMetalPick

#include "Basic.hpp"

#include "PrimalItem_WeaponBasePick_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_WeaponMetalPick.PrimalItem_WeaponMetalPick_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItem_WeaponMetalPick_C final : public UPrimalItem_WeaponBasePick_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponMetalPick_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_WeaponMetalPick_C")
	}
	static class UPrimalItem_WeaponMetalPick_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponMetalPick_C>();
	}
};

SDK_NAMESPACE_END
