#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_TekShirt_V2

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkin_TekShirt_V2.PrimalItemSkin_TekShirt_V2_C
// 0x0030 (0x0D80 - 0x0D50)
class UPrimalItemSkin_TekShirt_V2_C final : public UPrimalItemSkinGeneric_C
{
public:
	struct FTransform                             TekSuitVFXOffset;                                  // 0x0D50(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void BlueprintUnequipped();
	void BlueprintEquipped(bool bIsFromSaveGame);
	void RemovedSkinFromItem(class UPrimalItem* FromOwnerItem, bool bIsFirstTime);
	void ApplyingSkinOntoItem(class UPrimalItem* ToOwnerItem, bool bIsFirstTime);
	void TrySetTeksuitVFXOffset(bool Unequip);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_TekShirt_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkin_TekShirt_V2_C")
	}
	static class UPrimalItemSkin_TekShirt_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_TekShirt_V2_C>();
	}
};

SDK_NAMESPACE_END
