#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_Spawner_HoverSail_Parent

#include "Basic.hpp"

#include "PrimalItem_DinoSpawner_Base_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItem_Spawner_HoverSail_Parent.PrimalItem_Spawner_HoverSail_Parent_C
// 0x00C0 (0x0F60 - 0x0EA0)
#pragma pack(push, 0x1)
class SDK_ALIGN(0x10) UPrimalItem_Spawner_HoverSail_Parent_C : public UPrimalItem_DinoSpawner_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_PrimalItem_Spawner_HoverSail_Parent_C; // 0x0EA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         NumSpawnAttempts;                                  // 0x0EA8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EAC[0x4];                                      // 0x0EAC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AShooterCharacter*                      CraftingShooterChar;                               // 0x0EB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EB8[0x8];                                      // 0x0EB8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             SpawnTransform;                                    // 0x0EC0(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	class FString                                 SkiffSpawnString;                                  // 0x0EF0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class APrimalDinoCharacter*                   spawned_dino;                                      // 0x0F00(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         allowed_distance_to_despawn_hoversail;             // 0x0F08(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          should_have_a_spawned_dino;                        // 0x0F0C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_F0D[0x3];                                      // 0x0F0D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 lost_reference_string;                             // 0x0F10(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          could_find_a_valid_location_next_to_target;        // 0x0F20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F21[0x7];                                      // 0x0F21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 usetofollowstring;                                 // 0x0F28(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 use_to_deploy_string;                              // 0x0F38(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 use_to_put_away_string;                            // 0x0F48(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          show_appropriate_item_description_based_on_state___not_working_on_dedi; // 0x0F58(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_PrimalItem_Spawner_HoverSail_Parent(int32 EntryPoint);
	void SpawnCraftedSkiff();
	bool BPCanUse(bool bIgnoreCooldown);
	void Delaymount();
	void notify_hoversail_destroyed();
	class FString BPGetItemDescription(const class FString& InDescription, bool bGetLongDescription, class AShooterPlayerController* ForPC);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_Spawner_HoverSail_Parent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItem_Spawner_HoverSail_Parent_C")
	}
	static class UPrimalItem_Spawner_HoverSail_Parent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_Spawner_HoverSail_Parent_C>();
	}
};
#pragma pack(pop)

SDK_NAMESPACE_END
