#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_TekRoof

#include "Basic.hpp"

#include "PrimalItemStructure_BaseRoof_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemStructure_TekRoof.PrimalItemStructure_TekRoof_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemStructure_TekRoof_C final : public UPrimalItemStructure_BaseRoof_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemStructure_TekRoof_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemStructure_TekRoof_C")
	}
	static class UPrimalItemStructure_TekRoof_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemStructure_TekRoof_C>();
	}
};

SDK_NAMESPACE_END
