#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemSkin_CorruptedPants

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemSkin_CorruptedPants.PrimalItemSkin_CorruptedPants_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemSkin_CorruptedPants_C final : public UPrimalItemSkinGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemSkin_CorruptedPants_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemSkin_CorruptedPants_C")
	}
	static class UPrimalItemSkin_CorruptedPants_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemSkin_CorruptedPants_C>();
	}
};

SDK_NAMESPACE_END
