#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_BaseBoots

#include "Basic.hpp"

#include "PrimalItemArmorGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemArmor_BaseBoots.PrimalItemArmor_BaseBoots_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemArmor_BaseBoots_C : public UPrimalItemArmorGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_BaseBoots_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemArmor_BaseBoots_C")
	}
	static class UPrimalItemArmor_BaseBoots_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_BaseBoots_C>();
	}
};

SDK_NAMESPACE_END
