#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PurchaseButtonFace

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass PurchaseButtonFace.PurchaseButtonFace_C
// 0x0018 (0x0328 - 0x0310)
class UPurchaseButtonFace_C final : public UPrimalUserWidget
{
public:
	uint8                                         Pad_30C[0x4];                                      // 0x030C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCanvasPanel*                           HasKeys;                                           // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           NeedsKeys;                                         // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         KeysNeeded;                                        // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         KeysHas;                                           // 0x0324(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void SetKeysNeeded(int32 Num, int32 HaveKeys);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PurchaseButtonFace_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PurchaseButtonFace_C")
	}
	static class UPurchaseButtonFace_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPurchaseButtonFace_C>();
	}
};

SDK_NAMESPACE_END
