#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SavePaintingEntryUI

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass SavePaintingEntryUI.SavePaintingEntryUI_C
// 0x0020 (0x06B8 - 0x0698)
class USavePaintingEntryUI_C final : public UUI_SavePainting
{
public:
	class UCustomButtonWidget*                    Close;                                             // 0x0698(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       Filename;                                          // 0x06A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_161;                                         // 0x06A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCustomButtonWidget*                    SetButton;                                         // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SavePaintingEntryUI_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"SavePaintingEntryUI_C")
	}
	static class USavePaintingEntryUI_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USavePaintingEntryUI_C>();
	}
};

SDK_NAMESPACE_END
