#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpaceWhale_Character_Base_BP

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function SpaceWhale_Character_Base_BP.SpaceWhale_Character_Base_BP_C.OnSaddleEquipped
// 0x0001 (0x0001 - 0x0000)
struct SpaceWhale_Character_Base_BP_C_OnSaddleEquipped final
{
public:
	bool                                          Equipped;                                          // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
