#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SpaceWhale_Character_Base_BP

#include "Basic.hpp"

#include "Dino_Character_BP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass SpaceWhale_Character_Base_BP.SpaceWhale_Character_Base_BP_C
// 0x0000 (0x2650 - 0x2650)
class ASpaceWhale_Character_Base_BP_C final : public ADino_Character_BP_C
{
public:
	void OnSaddleEquipped(bool Equipped);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SpaceWhale_Character_Base_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"SpaceWhale_Character_Base_BP_C")
	}
	static class ASpaceWhale_Character_Base_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASpaceWhale_Character_Base_BP_C>();
	}
};

SDK_NAMESPACE_END
