#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tek_DinoLaser_TrailEmitter

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Tek_DinoLaser_TrailEmitter.Tek_DinoLaser_TrailEmitter_C
// 0x0000 (0x0490 - 0x0490)
class ATek_DinoLaser_TrailEmitter_C final : public APrimalEmitterSpawnable
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Tek_DinoLaser_TrailEmitter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"Tek_DinoLaser_TrailEmitter_C")
	}
	static class ATek_DinoLaser_TrailEmitter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATek_DinoLaser_TrailEmitter_C>();
	}
};

SDK_NAMESPACE_END
