#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ThatchDoorPlacementEmitter

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass ThatchDoorPlacementEmitter.ThatchDoorPlacementEmitter_C
// 0x0000 (0x0490 - 0x0490)
class AThatchDoorPlacementEmitter_C final : public APrimalEmitterSpawnable
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ThatchDoorPlacementEmitter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"ThatchDoorPlacementEmitter_C")
	}
	static class AThatchDoorPlacementEmitter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AThatchDoorPlacementEmitter_C>();
	}
};

SDK_NAMESPACE_END
