#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TransferDialog

#include "Basic.hpp"

#include "TransferDialog_classes.hpp"
#include "TransferDialog_parameters.hpp"


SDK_NAMESPACE_START

// Function TransferDialog.TransferDialog_C.ExecuteUbergraph_TransferDialog
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransferDialog_C::ExecuteUbergraph_TransferDialog(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "ExecuteUbergraph_TransferDialog");

	Params::TransferDialog_C_ExecuteUbergraph_TransferDialog Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.BndEvt__TransferDialog_TheSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransferDialog_C::BndEvt__TransferDialog_TheSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature(float Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "BndEvt__TransferDialog_TheSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature");

	Params::TransferDialog_C_BndEvt__TransferDialog_TheSlider_K2Node_ComponentBoundEvent_2_OnFloatValueChangedEvent__DelegateSignature Parms{};

	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.Setup
// (Event, Public, BlueprintEvent)
// Parameters:
// class UPrimalItem*                      WithItem                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MaxQuantity                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bToRemote                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UTransferDialog_C::Setup(class UPrimalItem* WithItem, int32 MaxQuantity, bool bToRemote)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "Setup");

	Params::TransferDialog_C_Setup Parms{};

	Parms.WithItem = WithItem;
	Parms.MaxQuantity = MaxQuantity;
	Parms.bToRemote = bToRemote;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.SetCancelButtonText
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      WithText                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UTransferDialog_C::SetCancelButtonText(const class FText& WithText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "SetCancelButtonText");

	Params::TransferDialog_C_SetCancelButtonText Parms{};

	Parms.WithText = std::move(WithText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.SetAcceptButtonText
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const class FText&                      WithText                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UTransferDialog_C::SetAcceptButtonText(const class FText& WithText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "SetAcceptButtonText");

	Params::TransferDialog_C_SetAcceptButtonText Parms{};

	Parms.WithText = std::move(WithText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransferDialog_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "Tick");

	Params::TransferDialog_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransferDialog.TransferDialog_C.BndEvt__ConfirmationDialogGeneric_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UTransferDialog_C::BndEvt__ConfirmationDialogGeneric_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "BndEvt__ConfirmationDialogGeneric_CancelButton_K2Node_ComponentBoundEvent_1_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TransferDialog.TransferDialog_C.BndEvt__ConfirmationDialogGeneric_AcceptButton_K2Node_ComponentBoundEvent_0_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void UTransferDialog_C::BndEvt__ConfirmationDialogGeneric_AcceptButton_K2Node_ComponentBoundEvent_0_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "BndEvt__ConfirmationDialogGeneric_AcceptButton_K2Node_ComponentBoundEvent_0_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TransferDialog.TransferDialog_C.UpdateTitle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UTransferDialog_C::UpdateTitle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TransferDialog_C", "UpdateTitle");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
