#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TribeMemberButton

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass TribeMemberButton.TribeMemberButton_C
// 0x0008 (0x0688 - 0x0680)
class UTribeMemberButton_C final : public UTribeMemberButtonWidget
{
public:
	class UCustomButtonWidget*                    Button;                                            // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TribeMemberButton_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"TribeMemberButton_C")
	}
	static class UTribeMemberButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTribeMemberButton_C>();
	}
};

SDK_NAMESPACE_END
