#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_TouchCheckBox

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "ShooterGame_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_TouchCheckBox.W_TouchCheckBox_C
// 0x0078 (0x0430 - 0x03B8)
class UW_TouchCheckBox_C final : public UTouchCheckBox
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCheckBox*                              AttachmentCheckBox;                                // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTopLeftButton*                         MyButton;                                          // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_1;                                         // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBoxAttachment;                                 // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBoxTargeting;                                  // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	float                                         In_Height_Override;                                // 0x03E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3EC[0x4];                                      // 0x03EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(const struct FGeometry& Geometry, const struct FPointerEvent& InGestureEvent)> OnPressed; // 0x03F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FGeometry& Geometry, const struct FPointerEvent& InGestureEvent)> OnRelease; // 0x0400(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(const struct FGeometry& Geometry, const struct FPointerEvent& InGestureEvent)> OnMove; // 0x0410(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UTouchManager*                          TouchManager;                                      // 0x0420(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp;                                              // 0x0428(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         fillPeriod;                                        // 0x042C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_W_TouchCheckBox(int32 EntryPoint);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void BndEvt__W_TouchCheckBox_MyButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void OnButtonTouchEndedBP(const struct FGeometry& InGeometry, const struct FPointerEvent& InGestureEvent);
	void OnButtonTouchMovedBP(const struct FGeometry& InGeometry, const struct FPointerEvent& InGestureEvent);
	void OnButtonTouchStartedBP(const struct FGeometry& InGeometry, const struct FPointerEvent& InGestureEvent);
	void PreConstruct(bool IsDesignTime);
	void Construct();
	bool IsChecked();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_TouchCheckBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"W_TouchCheckBox_C")
	}
	static class UW_TouchCheckBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_TouchCheckBox_C>();
	}
};

SDK_NAMESPACE_END
