#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterTap_Base

#include "Basic.hpp"

#include "StructureItemContainerBaseBP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WaterTap_Base.WaterTap_Base_C
// 0x0008 (0x0ED0 - 0x0EC8)
class AWaterTap_Base_C final : public AStructureItemContainerBaseBP_C
{
public:
	class UPrimalInventoryBP_Tap_C*               PrimalInventoryBP_Tap_C1;                          // 0x0EC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterTap_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"WaterTap_Base_C")
	}
	static class AWaterTap_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWaterTap_Base_C>();
	}
};

SDK_NAMESPACE_END
