#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeapFists

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass WeapFists.WeapFists_C
// 0x0000 (0x0D50 - 0x0D50)
class AWeapFists_C : public AShooterWeapon_Melee
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WeapFists_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"WeapFists_C")
	}
	static class AWeapFists_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWeapFists_C>();
	}
};

SDK_NAMESPACE_END
