#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AppsFlyerSDK

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.advertisingIdentifier
// 0x0010 (0x0010 - 0x0000)
struct AppsFlyerSDKBlueprint_advertisingIdentifier final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.getAppsFlyerUID
// 0x0010 (0x0010 - 0x0000)
struct AppsFlyerSDKBlueprint_getAppsFlyerUID final
{
public:
	class FString                                 ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.logEvent
// 0x0060 (0x0060 - 0x0000)
struct AppsFlyerSDKBlueprint_logEvent final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMap<class FString, class FString>            Values;                                            // 0x0010(0x0050)(Parm, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.setAdditionalData
// 0x0050 (0x0050 - 0x0000)
struct AppsFlyerSDKBlueprint_setAdditionalData final
{
public:
	TMap<class FString, class FString>            CustomData;                                        // 0x0000(0x0050)(Parm, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.SetConsentForGDPRUser
// 0x0002 (0x0002 - 0x0000)
struct AppsFlyerSDKBlueprint_SetConsentForGDPRUser final
{
public:
	bool                                          hasConsentForDataUsage;                            // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          hasConsentForAdsPersonalization;                   // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.setCustomerUserId
// 0x0010 (0x0010 - 0x0000)
struct AppsFlyerSDKBlueprint_setCustomerUserId final
{
public:
	class FString                                 customerUserId;                                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.setRemoteNotificationsToken
// 0x0010 (0x0010 - 0x0000)
struct AppsFlyerSDKBlueprint_setRemoteNotificationsToken final
{
public:
	TArray<uint8>                                 Token;                                             // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function AppsFlyerSDK.AppsFlyerSDKBlueprint.waitForATTUserAuthorizationWithTimeoutInterval
// 0x0004 (0x0004 - 0x0000)
struct AppsFlyerSDKBlueprint_waitForATTUserAuthorizationWithTimeoutInterval final
{
public:
	int32                                         timeoutInterval;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
