#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AttackMove_DR

#include "Basic.hpp"

#include "AIModule_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass AttackMove_DR.AttackMove_DR_C
// 0x0008 (0x00A0 - 0x0098)
class UAttackMove_DR_C final : public UBTDecorator_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_AttackMove_DR(int32 EntryPoint);
	void ReceiveConditionCheck(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AttackMove_DR_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AttackMove_DR_C")
	}
	static class UAttackMove_DR_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAttackMove_DR_C>();
	}
};

SDK_NAMESPACE_END
