#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioCapture

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "AudioMixer_classes.hpp"


SDK_NAMESPACE_START

// Class AudioCapture.AudioCaptureComponent
// 0x00E0 (0x07C0 - 0x06E0)
class UAudioCaptureComponent final : public USynthComponent
{
public:
	int32                                         JitterLatencyFrames;                               // 0x06E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_6E4[0xDC];                                     // 0x06E4(0x00DC)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioCaptureComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioCaptureComponent")
	}
	static class UAudioCaptureComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioCaptureComponent>();
	}
};

// Class AudioCapture.AudioCaptureFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UAudioCaptureFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UAudioCapture* CreateAudioCapture();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioCaptureFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioCaptureFunctionLibrary")
	}
	static class UAudioCaptureFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioCaptureFunctionLibrary>();
	}
};

// Class AudioCapture.AudioCapture
// 0x0008 (0x00C8 - 0x00C0)
class UAudioCapture final : public UAudioGenerator
{
public:
	uint8                                         Pad_C0[0x8];                                       // 0x00C0(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	bool GetAudioCaptureDeviceInfo(struct FAudioCaptureDeviceInfo* OutInfo);
	bool IsCapturingAudio();
	void StartCapturingAudio();
	void StopCapturingAudio();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AudioCapture")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"AudioCapture")
	}
	static class UAudioCapture* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioCapture>();
	}
};

SDK_NAMESPACE_END
