#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CactusHarvestComponent

#include "Basic.hpp"

#include "AttackHarvestComponent_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass CactusHarvestComponent.CactusHarvestComponent_C
// 0x0010 (0x0260 - 0x0250)
class UCactusHarvestComponent_C final : public UAttackHarvestComponent_Base_C
{
public:
	float                                         PlayerGiveWaterAmount;                             // 0x0250(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PlayerGiveWaterSpeed;                              // 0x0254(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MorellatopsGiveWaterAmount;                        // 0x0258(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	int32 BPCustomHarvestResource(class UPrimalInventoryComponent* invComp, int32 NumToGive, TSubclassOf<class UDamageType> DamageTypeClass, class AActor* ToActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CactusHarvestComponent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"CactusHarvestComponent_C")
	}
	static class UCactusHarvestComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCactusHarvestComponent_C>();
	}
};

SDK_NAMESPACE_END
