#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: camelsaurus_Character_Base_BP

#include "Basic.hpp"

#include "Dino_Character_BP_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass camelsaurus_Character_Base_BP.camelsaurus_Character_Base_BP_C
// 0x0010 (0x2660 - 0x2650)
class Acamelsaurus_Character_Base_BP_C final : public ADino_Character_BP_C
{
public:
	float                                         WaterAmount;                                       // 0x2650(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, SaveGame, IsPlainOldData, NoDestructor, PersistentInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxWaterAmount;                                    // 0x2654(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AddWater(float Amount, float* NewWaterAmount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("camelsaurus_Character_Base_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"camelsaurus_Character_Base_BP_C")
	}
	static class Acamelsaurus_Character_Base_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Acamelsaurus_Character_Base_BP_C>();
	}
};

SDK_NAMESPACE_END
