#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DestroyedMeshBase

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass DestroyedMeshBase.DestroyedMeshBase_C
// 0x0000 (0x0408 - 0x0408)
class ADestroyedMeshBase_C final : public ADestroyedMeshActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DestroyedMeshBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"DestroyedMeshBase_C")
	}
	static class ADestroyedMeshBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADestroyedMeshBase_C>();
	}
};

SDK_NAMESPACE_END
