#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EggIncubatorInterface

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function EggIncubatorInterface.EggIncubatorInterface_C.GetItemDisplaySlot
// 0x0010 (0x0010 - 0x0000)
struct EggIncubatorInterface_C_GetItemDisplaySlot final
{
public:
	class UPrimalItem*                            ForItem;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         InSlot;                                            // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SlotFound;                                         // 0x000C(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

// Function EggIncubatorInterface.EggIncubatorInterface_C.IsEggItemAllowed
// 0x0010 (0x0010 - 0x0000)
struct EggIncubatorInterface_C_IsEggItemAllowed final
{
public:
	class UPrimalItemConsumable_Egg_C*            EggItem;                                           // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsAllowed;                                         // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
