#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GetRandomFleePoint_TK

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GetRandomFleePoint_TK.GetRandomFleePoint_TK_C
// 0x0038 (0x00E0 - 0x00A8)
class UGetRandomFleePoint_TK_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         FixedDistance;                                     // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RandomDistance;                                    // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FBlackboardKeySelector                 NavigationTargetKey;                               // 0x00B8(0x0028)(Edit, BlueprintVisible)

public:
	void ExecuteUbergraph_GetRandomFleePoint_TK(int32 EntryPoint);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GetRandomFleePoint_TK_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"GetRandomFleePoint_TK_C")
	}
	static class UGetRandomFleePoint_TK_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGetRandomFleePoint_TK_C>();
	}
};

SDK_NAMESPACE_END
