#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MediaIOCore

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// Enum MediaIOCore.EFileMediaOutputPixelFormat
// NumValues: 0x0003
enum class EFileMediaOutputPixelFormat : uint32
{
	B8G8R8A8                                 = static_cast<uint32>(0),
	FloatRGBA                                = static_cast<uint32>(1),
	EFileMediaOutputPixelFormat_MAX          = static_cast<uint32>(2),
};

// Enum MediaIOCore.EMediaCaptureCroppingType
// NumValues: 0x0005
enum class EMediaCaptureCroppingType : uint8
{
	None                                     = static_cast<uint8>(0),
	Center                                   = static_cast<uint8>(1),
	TopLeft                                  = static_cast<uint8>(2),
	Custom                                   = static_cast<uint8>(3),
	EMediaCaptureCroppingType_MAX            = static_cast<uint8>(4),
};

// Enum MediaIOCore.EMediaCaptureState
// NumValues: 0x0006
enum class EMediaCaptureState : uint8
{
	Error                                    = static_cast<uint8>(0),
	Capturing                                = static_cast<uint8>(1),
	Preparing                                = static_cast<uint8>(2),
	StopRequested                            = static_cast<uint8>(3),
	Stopped                                  = static_cast<uint8>(4),
	EMediaCaptureState_MAX                   = static_cast<uint8>(5),
};

// Enum MediaIOCore.EMediaIOReferenceType
// NumValues: 0x0004
enum class EMediaIOReferenceType : uint32
{
	FreeRun                                  = static_cast<uint32>(0),
	External                                 = static_cast<uint32>(1),
	Input                                    = static_cast<uint32>(2),
	EMediaIOReferenceType_MAX                = static_cast<uint32>(3),
};

// Enum MediaIOCore.EMediaIOOutputType
// NumValues: 0x0003
enum class EMediaIOOutputType : uint32
{
	Fill                                     = static_cast<uint32>(0),
	FillAndKey                               = static_cast<uint32>(1),
	EMediaIOOutputType_MAX                   = static_cast<uint32>(2),
};

// Enum MediaIOCore.EMediaIOInputType
// NumValues: 0x0003
enum class EMediaIOInputType : uint32
{
	Fill                                     = static_cast<uint32>(0),
	FillAndKey                               = static_cast<uint32>(1),
	EMediaIOInputType_MAX                    = static_cast<uint32>(2),
};

// Enum MediaIOCore.EMediaIOTimecodeFormat
// NumValues: 0x0004
enum class EMediaIOTimecodeFormat : uint8
{
	None                                     = static_cast<uint8>(0),
	LTC                                      = static_cast<uint8>(1),
	VITC                                     = static_cast<uint8>(2),
	EMediaIOTimecodeFormat_MAX               = static_cast<uint8>(3),
};

// Enum MediaIOCore.EMediaIOStandardType
// NumValues: 0x0004
enum class EMediaIOStandardType : uint32
{
	Progressive                              = static_cast<uint32>(0),
	Interlaced                               = static_cast<uint32>(1),
	ProgressiveSegmentedFrame                = static_cast<uint32>(2),
	EMediaIOStandardType_MAX                 = static_cast<uint32>(3),
};

// Enum MediaIOCore.EMediaIOQuadLinkTransportType
// NumValues: 0x0003
enum class EMediaIOQuadLinkTransportType : uint32
{
	SquareDivision                           = static_cast<uint32>(0),
	TwoSampleInterleave                      = static_cast<uint32>(1),
	EMediaIOQuadLinkTransportType_MAX        = static_cast<uint32>(2),
};

// Enum MediaIOCore.EMediaIOTransportType
// NumValues: 0x0005
enum class EMediaIOTransportType : uint32
{
	SingleLink                               = static_cast<uint32>(0),
	DualLink                                 = static_cast<uint32>(1),
	QuadLink                                 = static_cast<uint32>(2),
	HDMI                                     = static_cast<uint32>(3),
	EMediaIOTransportType_MAX                = static_cast<uint32>(4),
};

// ScriptStruct MediaIOCore.MediaIODevice
// 0x000C (0x000C - 0x0000)
struct FMediaIODevice final
{
public:
	class FName                                   DeviceName;                                        // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DeviceIdentifier;                                  // 0x0008(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaIOConnection
// 0x0020 (0x0020 - 0x0000)
struct FMediaIOConnection final
{
public:
	struct FMediaIODevice                         Device;                                            // 0x0000(0x000C)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	class FName                                   protocol;                                          // 0x000C(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMediaIOTransportType                         TransportType;                                     // 0x0014(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMediaIOQuadLinkTransportType                 QuadTransportType;                                 // 0x0018(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PortIdentifier;                                    // 0x001C(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaIOMode
// 0x0018 (0x0018 - 0x0000)
struct FMediaIOMode final
{
public:
	struct FFrameRate                             FrameRate;                                         // 0x0000(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FIntPoint                              Resolution;                                        // 0x0008(0x0008)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMediaIOStandardType                          Standard;                                          // 0x0010(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DeviceModeIdentifier;                              // 0x0014(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaIOConfiguration
// 0x003C (0x003C - 0x0000)
struct FMediaIOConfiguration final
{
public:
	bool                                          bIsInput;                                          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMediaIOConnection                     MediaConnection;                                   // 0x0004(0x0020)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	struct FMediaIOMode                           MediaMode;                                         // 0x0024(0x0018)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaIOInputConfiguration
// 0x0044 (0x0044 - 0x0000)
struct FMediaIOInputConfiguration final
{
public:
	struct FMediaIOConfiguration                  MediaConfiguration;                                // 0x0000(0x003C)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	EMediaIOInputType                             inputType;                                         // 0x003C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         KeyPortIdentifier;                                 // 0x0040(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaIOOutputConfiguration
// 0x004C (0x004C - 0x0000)
struct FMediaIOOutputConfiguration final
{
public:
	struct FMediaIOConfiguration                  MediaConfiguration;                                // 0x0000(0x003C)(Edit, EditConst, NoDestructor, NativeAccessSpecifierPublic)
	EMediaIOOutputType                            OutputType;                                        // 0x003C(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         KeyPortIdentifier;                                 // 0x0040(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMediaIOReferenceType                         OutputReference;                                   // 0x0044(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ReferencePortIdentifier;                           // 0x0048(0x0004)(Edit, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// ScriptStruct MediaIOCore.MediaCaptureOptions
// 0x0010 (0x0010 - 0x0000)
struct FMediaCaptureOptions final
{
public:
	EMediaCaptureCroppingType                     Crop;                                              // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FIntPoint                              CustomCapturePoint;                                // 0x0004(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bResizeSourceBuffer;                               // 0x000C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSkipFrameWhenRunningExpensiveTasks;               // 0x000D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

SDK_NAMESPACE_END
