#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MRMesh

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum MRMesh.EMeshTrackerVertexColorMode
// NumValues: 0x0004
enum class EMeshTrackerVertexColorMode : uint8
{
	None                                     = static_cast<uint8>(0),
	Confidence                               = static_cast<uint8>(1),
	Block                                    = static_cast<uint8>(2),
	EMeshTrackerVertexColorMode_MAX          = static_cast<uint8>(3),
};

// ScriptStruct MRMesh.MRMeshConfiguration
// 0x0001 (0x0001 - 0x0000)
struct FMRMeshConfiguration final
{
public:
	uint8                                         Pad_0[0x1];                                        // 0x0000(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

SDK_NAMESPACE_END
