#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemResource_Flint

#include "Basic.hpp"

#include "PrimalItemResourceGeneric_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemResource_Flint.PrimalItemResource_Flint_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemResource_Flint_C final : public UPrimalItemResourceGeneric_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemResource_Flint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemResource_Flint_C")
	}
	static class UPrimalItemResource_Flint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemResource_Flint_C>();
	}
};

SDK_NAMESPACE_END
