#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemAmmo_SimpleBullet

#include "Basic.hpp"

#include "PrimalItemAmmo_Base_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass PrimalItemAmmo_SimpleBullet.PrimalItemAmmo_SimpleBullet_C
// 0x0000 (0x0D50 - 0x0D50)
class UPrimalItemAmmo_SimpleBullet_C final : public UPrimalItemAmmo_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemAmmo_SimpleBullet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(u"PrimalItemAmmo_SimpleBullet_C")
	}
	static class UPrimalItemAmmo_SimpleBullet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemAmmo_SimpleBullet_C>();
	}
};

SDK_NAMESPACE_END
